# Generated by Django 5.0 on 2024-01-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=40, unique=True, verbose_name='Email')),
                ('phonenumber', models.CharField(max_length=13, unique=True, verbose_name='Phone_Number')),
                ('bio', models.CharField(blank=True, max_length=40, verbose_name='Bio')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profilepic/', verbose_name='Profile_Pic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
