# Generated by Django 5.0 on 2024-01-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_customusermodel_is_active_customusermodel_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='phonenumber',
            field=models.CharField(max_length=13, verbose_name='Phone Number'),
        ),
    ]
