# Generated by Django 5.0 on 2024-01-01 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_alter_customusermodel_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 16, 16, 51, 510053, tzinfo=datetime.timezone.utc), verbose_name='last login'),
        ),
    ]
