# Generated by Django 5.0 on 2024-01-01 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usermanagement', '0005_alter_customusermodel_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='last_login',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 16, 24, 59, 918444, tzinfo=datetime.timezone.utc), verbose_name='last login'),
        ),
    ]
